apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-petclinic
  template:
    metadata:
      labels:
        app: springboot-petclinic
    spec:
      containers:
      - name: springboot-container
        image: springbootpetclinicacr.azurecr.io/petclinic:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-petclinic # This should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 8080 # Port exposed by your application
      targetPort: 8080 # Port your application listens on
  type: LoadBalancer # Use LoadBalancer type to expose externally (specific to cloud providers)
