name: Deploy to AKS Cluster
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: springbootpetclinicacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -t springbootpetclinicacr.azurecr.io/springbootimage:${{ github.sha }}
        docker push springbootpetclinicacr.azurecr.io/springbootimage:${{ github.sha }}
      
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: springbootpetclinicaks
        resource-group: myresourcegroup
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: springbootpetclinicacr.azurecr.io
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          springbootpetclinicacr.azurecr.io/springbootimage:${{ github.sha }}
        imagepullsecrets: |
          k8s-secret